
package interfaces;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;



public class IUPrincipal extends javax.swing.JFrame {

   
    public IUPrincipal() {
        setTitle("Pantalla principal");
        initComponents();
        setResizable(false);
        setLocation(20, 30);
        setSize(400, 300);
        
        ImageIcon wallpaper = new ImageIcon("src/images/fondo.png");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_DEFAULT));
        jLabel3.setIcon(icono);
        this.repaint();
        
        this.setVisible(true);
    }
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/UTNIcono.png"));
        return retValue;     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPrestamo = new javax.swing.JMenu();
        menuRegistrarReserva = new javax.swing.JMenuItem();
        menuConsultarPrestamo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuGestionarRecursos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuGestionarUsuarios = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuDesarrollador = new javax.swing.JMenuItem();
        menuVersion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel1.setText("INTERFAZ DE GESTIÓN - ÁREA TIC");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UTN.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 60, 100));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -16, 410, 490));

        menuPrestamo.setText("Reservas");

        menuRegistrarReserva.setText("Registrar reserva");
        menuPrestamo.add(menuRegistrarReserva);

        menuConsultarPrestamo.setText("Consultar Prestamos");
        menuPrestamo.add(menuConsultarPrestamo);

        jMenuBar1.add(menuPrestamo);

        jMenu2.setText("Recursos");

        menuGestionarRecursos.setText("Gestionar recursos");
        jMenu2.add(menuGestionarRecursos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Usuarios");

        menuGestionarUsuarios.setText("Gestionar usuarios");
        jMenu3.add(menuGestionarUsuarios);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Acerca de");

        menuDesarrollador.setText("Desarrollador");
        jMenu5.add(menuDesarrollador);

        menuVersion.setText("Versión");
        jMenu5.add(menuVersion);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem menuConsultarPrestamo;
    public javax.swing.JMenuItem menuDesarrollador;
    public javax.swing.JMenuItem menuGestionarRecursos;
    public javax.swing.JMenuItem menuGestionarUsuarios;
    private javax.swing.JMenu menuPrestamo;
    public javax.swing.JMenuItem menuRegistrarReserva;
    public javax.swing.JMenuItem menuVersion;
    // End of variables declaration//GEN-END:variables
}
